name: basespace-dl
version: git
summary: Multi-account basespace file downloader
description: |
  Download files from projects across multiple basespace accounts.
  Features
    - Easy syntax `basespace-dl PROJECT`
    - Multiple accounts (one time config file setup)
    - Fast (concurrent fetching and downloading)
    - Only download what you need (using regex patterns)

grade: stable
confinement: devmode

parts:
  basespace-dl:
    plugin: rust
    source: .
    build-packages:
      - pkg-config
      - libssl-dev

apps:
  basespace-dl:
    command: bin/basespace-dl
