[package]
name = "basespace-dl"
version = "0.2.1"
authors = ["dweb0"]
description = "Multi-account basespace file downloader"
homepage = "https://github.com/dweb0/basespace-dl"
repository = "https://github.com/dweb0/basespace-dl"
readme = "README.md"
keywords = ["bioinformatics", "download", "downloader", "basespace"]
categories = ["command-line-interface"]
license = "MIT/Apache-2.0"
edition = "2018"
exclude = [
    "./.travis.yml", "./appveyor.yml", "./.snapcraft.yaml",
    "/build/*", "./screencast.svg"
]

[badges]
travis-ci = { repository = "dweb0/basespace-dl" }
appveyor = { repository = "dweb0/basespace-dl", service = "github" }

[[bin]]
name = "basespace-dl"
path = "src/main.rs"

[dependencies]
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
futures = "*"
tokio = "*"
clap = "*"
regex = "*"
dirs = "1.0"
termcolor = "*"
tokio-core = "*"
crossbeam-channel = "0.3"
toml = "*"
pretty-bytes = "*"
failure = "*"
console = "*"
text_io = "0.1.7"
rayon = "*"
md5 = "*"
env_logger = "*"
log = "*"
indicatif = "*"