[package]
name = "basespace-dl"
version = "0.2.3"
authors = ["dweb0"]
description = "Multi-account basespace file downloader"
homepage = "https://github.com/dweb0/basespace-dl"
repository = "https://github.com/dweb0/basespace-dl"
readme = "README.md"
keywords = ["bioinformatics", "download", "downloader", "basespace"]
categories = ["command-line-interface"]
license = "MIT/Apache-2.0"
edition = "2018"
exclude = [
    "./.travis.yml", "./appveyor.yml", "./.snapcraft.yaml",
    "/build/*", "./screencast.svg"
]

[badges]
travis-ci = { repository = "dweb0/basespace-dl" }
appveyor = { repository = "dweb0/basespace-dl", service = "github" }

[[bin]]
name = "basespace-dl"
path = "src/main.rs"

[dependencies]
reqwest = "0.9.22"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
futures = "0.1.29"
tokio = "0.1.22"
clap = "2.33.0"
regex = "1.3.1"
dirs = "2.0.2"
termcolor = "1.0.5"
tokio-core = "0.1.17"
crossbeam-channel = "0.3.9"
toml = "0.5.3"
pretty-bytes = "0.2.2"
failure = "0.1.6"
console = "0.9.0"
text_io = "0.1.7"
rayon = "1.2.0"
md5 = "0.6.1"
env_logger = "0.7.0"
log = "0.4.8"
indicatif = "0.12.0"
