[package]
name = "basespace-dl"
version = "0.1.0"
authors = ["daniel"]
edition = "2018"

[dependencies]
reqwest = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
futures = "*"
tokio = "*"
clap = "*"
regex = "*"
dirs = "1.0"
termcolor = "*"
tokio-core = "*"
crossbeam-channel = "0.3"
toml = "*"
pretty-bytes = "*"
failure = "*"
indicatif = "*"
console = "*"